language: ruby
rvm:
  - 2.4.1
before_install:
  - gem install bundler

before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate

  before_install:
    gem update --system

script:
  - bundle exec rspec

notifications:
  email: false
